### ISSUE TITLE
}{0\/\/ +0 |)154|}|_3???

### ISSUE THREAD

**Issue by ghost** [Megabyte918/leetspeak-keyboard#4]
}{0\/\/ +0 |)154|}|_3 |>|_3453!!!

**Comment by m-byte918** [comment]
@XtremePlayzCODE
<pre>
 (1!(|< +}{3 }{!|)|)3|\| !(0|\|5 |\/|3|\|(_), .-!6}{+ (1!(|< 133+5|>34|<.4}{|<, 4|\||) (1!(|< "5(_)5|>3|\||) }{0+|<3`/5"
</pre>

**Comment by ghost** [comment]
Ok, ok, please provide a real answer not in leet, I am using my iPhone now XD

**Comment by m-byte918** [comment]
Click the hidden icons menu, right click leetspeak.ahk, and click "suspend hotkeys" or "exit"

**Comment by ghost** [comment]
Ok thanks
